matrix:
  include:
    - language: python
      sudo: required
      python:
        - '3.7'
      cache: apt
      install:
        - pip install -r requirements.txt
        - python setup.py install
      script:
        - pytest
