name: Upload to S3

on:
  push:
    branches: [main]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Build docs
        run: |
          python -m pip install -r docs/requirements.txt
          cd docs; ./build.sh; cd -
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: docs-python.resgen.io
          source_dir: docs/_build/html
          destination_dir: ""
